require(__dirname + '/../app/js/entry');
require('angular-mocks');
require(__dirname + '/jedis_controller_test');
require(__dirname + '/sithlords_controller_test');
require(__dirname + '/resource_service_test');
require(__dirname + '/jedi_form_directive_test');
require(__dirname + '/jedi_display_directive_test');
require(__dirname + '/sith_display_directive_test');
require(__dirname + '/sith_form_directive_test');
require(__dirname + '/jedi_auth_test');
require(__dirname + '/signup_controller_test');
require(__dirname + '/signin_controller_test');
require(__dirname + '/user_auth_services_test');
